Makefile
README
file.c
gophernicus.c
gophernicus.h
menu.c
options.c

Using gophernicus on an experimental gopher server with git-only access for users ( gopher://dome.circumlunar.space ), I wanted to have the possibility to suppress processing of executables (gophermaps and scripts), therefore I added an -nx option and corresponding code. Seems to work on my system... Thanks for gophernicus, by the way! ^-^

add -nx flag to block execution of all files and scripts

---

menu.c

Whilst reading the sources of gophernicus, I've found a security problem.
```
/* Try to execute or open the mapfile */
#ifdef HAVE_POPEN
if (exe) {
setenv_cgi(st, mapfile);
if ((fp = popen(command, "r")) == NULL) return OK;
}
else
#endif
if ((fp = fopen(mapfile, "r")) == NULL) return OK;
/* Read lines one by one */
while (fgets(line, sizeof(line) - 1, fp)) {
```
If the system doesn't have `popen(3)`, then the contents of executable maps can be leaked to the client.
For example if I have a gophermap:
```
!test
run my script
=./script.sh
```
And an executable shell script in the same dir:
```
#!/bin/sh
/path/to/some/program --password topsecret
```
And I pretend my system doesn't have `popen(3)`:
```
diff --git a/menu.c b/menu.c
index 11004d3..3d9ef76 100644
--- a/menu.c
+++ b/menu.c
@@ …
```

Prevent possible leak of executable gophermap contents.

---

README
gophernicus.c
gophernicus.h
menu.c
options.c

Following in the spirit of `-nx`, I use gophernicus on a server with one one user (me) and I'd like it if gophernicus didn't try to look into `/home` at all.
This change adds a `-nu` flag which disables personal spaces.
I wrote this code a while back as part of a pledge/unveil diff for OpenBSD ports. I've peeled the addition of this flag off to make reviewing simpler.
(My end-goal is to unveil `/home` only if `-nx` is not supplied. Similarly, if `-nx` is supplied, gophernicus can be denied of the `getpw` promise, as it no longer needs to look up user `${HOME}`s.)
I need to re-test this, but I'm raising a draft PR to gauge reactions.
Cheers

Add -nu flag to disable personal spaces.

---

Makefile
README.md
version

I think it would be good to have the README in Markdown README.md format.
This requires some changes in the Makefile, as README.md does not work well as a C macro name, which is used for inclusion.
I also have changed the string flagging the end of the options list, and the corresponding sed for its extraction.
And the default version in case git log isn't available has been bumped to a more informative "110 or more" value.

bump default version, markdownify README and adapt Makefile

---

INSTALL
Makefile
README
README.md
file.c
gophernicus.c
gophernicus.h
menu.c
options.c
version

As-is, ```gophernicus``` will use ```systemd``` if that's present.  Perhaps the installer would rather use ```xinetd``` or ```inetd```, particularly if ```systemd``` support is troublesome (see #4).  This modification allows one to install ```gophernicus``` using those other two super-servers.

Allow for installation for xinetd or inetd when systemd is present.

---

INSTALL

I just now realized that I forgot to add mention to INSTALL about how to have Gophernicus use inetd or xinetd even if your OS uses systemd for whatever reason.

Mention using inetd or xinetd when systemd is present.

---

file.c

Per [issue 27](https://github.com/gophernicus/gophernicus/issues/27), I added `irc://` as an allowed protocol for redirects in `file.c`

Allowing irc:// as safe redirect in file.c

---

INSTALL.md

the git clone url was still for the repo's old location

fix url in INSTALL.md

---

.gitignore
INSTALL.md
Makefile
README.Gophermap
README.md
VERSIONING.md
changelog
debian/control
debian/gophernicus.templates
debian/prerm
debian/rules
gophernicus.c
gophernicus.h
gophernicus.xinetd
menu.c
options.c
platform.c

Fine with 3.0 -- here are just some small corrections and suggestions for reformatting, replacing "in.gophernicus" by "gophernicus" at several spots, as well as removals of trailing spaces and spurious cruft from old commits.
I've also added better explanation of hostname setting and noticed FreeBSD 12 as supported (because it runs well with inetd on several of my machines).

replace executable name, remove trailing spaces

---

gophernicus.h
options.c

These days, the vast majority of gopher servers and clients run using UTF-8. Let's change the default charset to utf-8, so that people can use Unicode characters easily and without modification to the options.
@hb9kns

change default charset to utf-8

---

README.md
gophernicus.c
gophernicus.h
options.c

Please don't merge this until another OpenBSD developer has checked my work.
This diff improves the security of Gophernicus when used on OpenBSD via `pledge(2)` and `unveil(2)`.
For more info on these APIs:
* https://man.openbsd.org/pledge
* https://man.openbsd.org/unveil
The only minor nit I have with my work is that we lose the ability to unveil if personal gopherspaces are enabled. The reason for this is that user homes are arbitrary paths, so simply unveiling `/home` wouldn't be right. We could add a switch which allows the user to specify which directories to unveil(2)... Not sure if it's worth it though and we already have so many switches.
Thanks

OpenBSD pledge(2) and unveil(2) support.

---

.travis.yml

Working and tested .travis.yml for gophernicus.
It complies the src/ on Linux and macOS with gcc and clang. After this it runs `sudo make install`

ci: New Travis system for linux and macOS builds and installs

---

Makefile

While working on a new feature I discovered that make returns an error because the documentation symlink already exists. This is not really useful when testing the install feature a lot. This PR force creates the symlink.

build: Force create symlink & travis build fix on macOS

---

gophernicus.1.man
src/gophernicus.c
src/gophernicus.h
src/options.c

I added option `-nH` to disable HTTP response to HTTP `GET` and `POST` requests.
A request starting with `GET` or `POST` will be handled like a normal Gopher selector.
This PR fixes issue #66.
I tested it by requesting the autogenerated `caps.txt` file.
Without `-nH`, the file is served:
```
$ ./src/gophernicus -r ./.travis/ <<EOF
GET /caps.txt
EOF
CAPS
##
##
CapsVersion=1
ExpireCapsAfter=1800
...
```
With `-nH`, we get an error.
```
$ ./src/gophernicus -nH -nf ./.travis/ <<EOF
GET /caps.txt
EOF
Error: File or directory not found! No such file or directory
```

Add option `-nH` to disable HTTP response to HTTP GET/POST requests (#66)

---

Makefile
src/menu.c

This PR fixes a potential resource leak, where the file pointer to the gophermap is not `pclose`d or `fclose`d if the first character of the line is a `*` or a `.`.
`fopen` calls `malloc`, so some memory is leaked if `fclose` is not called.
Without the patch:
```$ make -B
$ cat >gophermap <<EOF
*
EOF
$ valgrind --show-leak-kinds=all --leak-check=full -s ./src/gophernicus -nf -r . <<EOF
EOF
==18015== Memcheck, a memory error detector
==18015== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==18015== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==18015== Command: ./src/gophernicus -nf -r .
==18015== 
0install-sh                            2020-Apr-01 23:09    13.4 KB	/install-sh	doriath	70
.
==18015== 
==18015== HEAP SUMMARY:
==18015==     in use at …
```

Always close file pointer and propagate CFLAGS/LDFLAGS to recursive MAKE calls

---

src/menu.c

I searched for other leftover tabs with
```bash
$ git grep $'[^\t]\t'
```
and it seems like these were the last harmful ones.

Replace spurious tabs in menu with dashes (#81)

---

Makefile
gophernicus.1
src/file.c
src/gophernicus.c
src/gophernicus.h
src/log.c
src/menu.c
src/platform.c
src/session.c

Hi,
This branch fixes issue #42.
I tested it on Linux x86_64 (Ubuntu 19.10) and OpenBSD amd64 (6.6).
I served a local document root containing an executable `gophermap`:
```sh
#!/usr/bin/env sh
/usr/bin/env | sort
```
and tried various requests: regular request, HTTP GET/POST, TCP PROXY, non-existent name.
The log messages are printed to `/var/syslog` on Linux, and `/var/daemon` on OpenBSD.
When the `-d` option is used, the debug messages also appear in the `syslog`, and all messages are printed to `stderr`.
I checked the implementation of non-standard `LOG_UPTO` with this test program:
```c
#include <stdio.h>
#include <syslog.h>
#define _LOG_UPTO(pri)							\
(								\
((pri) == LOG_EMERG)   ? (LOG_MASK(LOG_EMERG)) :		\
((pri) == LOG_ALERT)   ? (LOG_MASK(LOG_EMERG) | …
```

Fix issue #42

---

src/gophernicus.c

`getcwd(3)` returns a `NULL` pointer when it fails, and a pointer to the buffer
when it succeeds. The array of characters (allocated on the stack) is not `NULL`,
so it cannot be used to check if `getcwd(3)` succeeded. Use the pointer
returned by `getcwd(3)` to check success.
This bug was found by Clang 12 (`-Wtautological-pointer-compare`).

Really check success of getcwd(3)

---

Makefile.in

DESTDIR when used in packaging can represent a temporary directory or fake root used for packaging the application, so using this value for modifying the listener config is not ideal, as the binary path will be incorrect in the resulting package.
This change is to update `Makefile.in` to remove `DESTDIR` from the `sed` calls, as `SBINDIR` should be enough to provide the full path for the binary.

Don't use DESTDIR for binary paths in listener

---

gophernicus.8

This fixes a couple of issue with the current manpage:
- document `-nu` (it's only present in the SYNOPSIS)
- fix every issue reported by `man -Tlint -l gophernicus.8` *
- fix the usage of the `Pa` macro
\* mandoc still complains about:
```
man: gophernicus.8:1:5: STYLE: Mdocdate missing: Dd April 13, 2020 (OpenBSD)
man: gophernicus.8: STYLE: RCS id missing: (OpenBSD)
```
but those are only relevant for the OpenBSD manpages, not third parties ones.

some manpage fixes

---

Makefile.in

'make install-root' now checks if there is an existing gophermap, if it does, it no longer overwrites it

Fix #92 properly

---

configure

When checking the features of the install program, send any output on stderr to /dev/null rather than to stdout.

Suppress stderr output when checking for install

---

src/menu.c

The existing JPEG detection logic is too restrictive because it checks for the file header "FF D8 FF E0", which only matches JFIF-type JPEG images... Meanwhile EXIF JPEG images are more common these days.
For reference:
FF D8 = JPEG SOI (Start of Image) header
FF-D8-FF-E0 = JFIF
FF-D8-FF-E1 = EXIF
FF-D8-FF-E2 = CIFF
FF-D8-FF-E8 = SPIFF
As you can see checking for the SOI + FF matches all extant types of JPEG images... Many implementations only check for the SOI, I think they are crazy. \o/

Update menu.c: Fix JPEG detection.

---

src/gophernicus.c

* `sendfd` and `recvfd` are not needed: gophernicus doesn't use sendmsg(2) nor recvmsg(2).
* `inet` its needed only for getpeername(2), but it's only called from init_state and is *before* pledging.
* `proc` is needed only when st.opt_exec is set.
I have only one doubt about `sendfd` and `recvfd`: those *may* be used by libwrap, but that's not available on OpenBSD anyway.  (a quick grep doesn't find anything in the libwrap sources, but I haven't studied it in depth.)

tightens pledge(2) promises

---

src/platform.c

Gophernicus currently thinks that Alpine Linux is called "Welcome/6.7" (seems to be extracting the OS name from /etc/issue and the version it's grabbing the kernel version)
This commit allows gophernicus to read /etc/alpine-release and display the OS name and version correctly (e.g. "Alpine Linux/3.20")

Update platform.c: Detect Alpine Linux properly.

---

src/gophernicus.c

This fixes an issue introduced in commit a00fa5330dd4. As the destination string produced by html_escape is not explicitly terminated by the function as introduced in this commit, the escaped URL in dest continues with characters found in memory that have not been overwritten, which essentially breaks the encoded URL. The behaviour prior to commit a00fa5330dd4 was as follows:
$ src/gophernicus <<<URL:https://example.com | grep Refresh
<META HTTP-EQUIV="Refresh" content="1;URL=https://example.com">
The broken behaviour since commit a00fa5330dd4 is this:
$ src/gophernicus <<<URL:https://example.com | grep Refresh
<META HTTP-EQUIV="Refresh" content="1;URL=https://example.comtps://example.com"">
Explicitly terminating the destination string by adding a zero byte seems to fix this; yet, since …

Explicitly terminate dest string in html_encode

---

src/file.c

Gophernicus features a hard-coded whitelist of safe protocols that are allowed for html-based redirects. This list currently consists of http, https, ftp, irc and mailto. As the gemini protocol is seeing an ever greater usage, some phloggers have already started to add 'hURL:gemini://' links to their gophermaps. Since the current whitelist already seems to be somewhat permissive, I hereby suggest adding the gemini protocol to it.

Add gemini:// to redirection whitelist
